### ISSUE TITLE
/groups/_groupId 公演の表示を改善する

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#10]
* #4 

の後。

2023.であったバグ
・開場中のものは一番上に表示されるはずだったのができていなかった
・空席があるのに満席と表示された
・再読み込みができていなかった？

とは別に不便だった意見としてあったのが、全10公演が常に表示されてるので多くて邪魔というものです。

# やり方

おそらく、表示バグについては、created内でticketsに関する情報をGETするという手法にすることで解決すると思います。

また、団体詳細ページ（/_groupId）では開場中(=整理券取得可能)の公演だけを表示し、全公演を確認するにはボタンを押させる、
押したときにスマホ画面であれば全画面に表示されるイメージ
(v-dialogのfullscreenのイメージ、[参考](https://v2.vuetifyjs.com/ja/components/dialogs/#fullscreen))
などがいいとおもいます。
v-tabsとかも良いかもしれません。
このあたりのデザインは議論しましょう。

開場中の公演だけを表示するというのは、全公演を新しい順にソートし、既に終わった公演を一番下に動かす、そして一番上の1,2個を表示することで実現できると思います。インフォメーションボード画面と同じ手法です([issue #537](https://github.com/hibiya-itchief/quaint-app/issues/537))

あとそれと、現在paper属性の公演を考慮したsortが行われていますが、来年はpaper属性は廃止するので削除して結構です。
(加筆、本番用のsort(ビルド用)はnuxtconfig.ts内にある)

もう一つメモですが、
公演の表示が正しくなされるかチェックするためのテストを何月かに全校負荷テスト的な感じで行う予定です。23年度のように、本番になって発覚することのないように。。。

**Comment by aozoraUS** [comment]
取り組みます

**Comment by hibiyahibiyahibiya** [comment]
#33
