### ISSUE TITLE
/help 本文がない

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#22]
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/4fe86519-2556-45e5-a19a-4b159e3bf18d)

https://quaint-wa.pages.dev/help/

文字が白い？のか？
CSSの範疇だとは思うんだけど……

**Comment by aozoraUS** [comment]
これとりあえず取り組んでみますね

**Comment by hibiyahibiyahibiya** [comment]
#29
