### ISSUE TITLE
/groups テキストボックスの下の空間を削除

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#25]
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/4e191c9b-10e8-4b93-a55d-3da4951ce722)

v-text-fieldのhide-details="auto"かtrueか,
参考(https://dev.classmethod.jp/articles/remove-vuetify-component-margin/)
で解決されるのではないかな、と

そのうえで、検索ボックスの下に空間が欲しければmarginかpaddingかをつける、の方が良い気がする

https://github.com/hibiya-itchief/quaint-wa/issues/26 と一緒に取り組んでほしい

**Comment by Umechazuke** [comment]
これやってみます

**Comment by hibiyahibiyahibiya** [comment]
#30
