### ISSUE TITLE
/groups 検索時のpタグと位置

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#26]
pタグ(検索結果何件、を表示する)のせいで
絞り込みのボタンなどがぴょこぴょこと動く
一切機能には関わらないがちょっと不満

https://github.com/hibiya-itchief/quaint-wa/issues/25 と一緒に取り組んでほしい

**Comment by Umechazuke** [comment]
こっちもやります

**Comment by hibiyahibiyahibiya** [comment]
#30
