### ISSUE TITLE
/_groups 団体をホバー (トップページも？)

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#28]
[西高のサイト](https://kinensai.tech/circles)に触発
(1Cにカーソルを合わせている)
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/66c021ef-8dcc-4ec5-acb5-ff65e6a52090)

こんな感じのをGroupCardでもやってください！！

トップページのご案内一覧の実装を参考にするとよいと思います

[実装技術](https://developer.mozilla.org/ja/docs/Web/CSS/:hover)

**Comment by aozoraUS** [comment]
<img width="2001" alt="スクリーンショット 2024-01-14 18 57 17" src="https://github.com/hibiya-itchief/quaint-wa/assets/74809407/e3dc4da8-5a9f-4c6a-bf5b-46d474778dbe">
西高校のサイト見られないんですけどGroupCardの上にマウスがあると少し拡大されるという認識であっていますか？

**Comment by hibiyahibiyahibiya** [comment]
今見られないんだ
それであってる
