### ISSUE TITLE
開発者用ページについて

### ISSUE THREAD

**Issue by aozoraUS** [hibiya-itchief/quaint-wa#31]
開発者ページでサイトの設定をできるようにしたいです。
具体的な設定項目は
- テーマカラー
- 開催日程
- 開催時刻
- テーマ（文化祭のテーマのこと（さいらい））
など最低限設定すればサイトとして運営できるようにする項目を考えています。

今はサイト開発の立ち上げメンバーが揃っているので開発を進めることができていますが、これからそのメンバーがどんどんと離れていった場合、このサイトを保持することは大きな負担になってしまうと思います。また有志の委員会なので十分な人数が以降確保できるかもわかりません。そのため、プログラムを書くことなくサイトのある程度の設定をできるようにしたいと考えています。

実際にこの機能が必要なのかを含めて、意見が欲しいです。

**Comment by aozoraUS** [comment]
開発者ページを作るのではなくサイトの設定ファイルを一つ作って、そこにサイトの情報を書くという方式でもいいかもしれません

**Comment by hibiyahibiyahibiya** [comment]
ちょっと思った事を書いとく

## テーマカラー

テーマカラーを決定するのは確かに開発者関係ないけど、テーマカラーって毎年あたり１つだよね
設定する回数が多くないから、開発者ページに入れ込む必要は薄いかなと
(毎年１回テーマカラーを変更する内容のcommit入れるだけでいいから)

それに、今は2023年度用のページを青に染色してるだけだけど、年々のテーマによってデザインも変わるだろうから、さらに言えばそもそもテーマカラーがひとつっていうシステムも固定されないだろうと思う
(メインカラー、サブカラー、アクセントカラー、みたいな)
から、そういう固定化された機能はどうなんだろうかなと

代替案として、ちょうどこのページを残してればいいんじゃないかな
これ：[テーマカラーの設定](https://hibiya-itchief.github.io/quaint-docs/developer/front/theme-color/)
これが手元にあれば10分もいらないと思うし
それか、こういう大きな単位での「サイトの設定」についてはpdfとかに改めてまとめるのもありかもね

## 開催日程時刻

同じように、設定するのは毎年一度だけだし、さらに固定された様式とは限らないかもというところ

## テーマページ？

認識が違ったらごめん
このあたりは、正直来年がどういう様式になるかわかんないけど、そこまで開発者はいらないんじゃあないかなとは思う
本文を書くのはチーフに任せたり、とかね
ただ、ページを作る部分まで、どうやって開発者ページで実現するのか思いつかなくて……
だったらいつも通りVSCodeで開発するので良くない？ってなっちゃった()


## .

開発者に頼りすぎないで運営ができるようにできたらいいよね～～～
っていうのは同意する

ただ、(おれの持論だと、)開発できる状態になるまでのハードルをできるだけ下げることぐらいしかできないかなと思ってる
（イメージ的には、入学時、何も知らない状態から、1,2か月程度でおれらと同程度に書ける状態に育てられたらいいな、の感じ）
具体的にはWikiとかpdfとか

**Comment by aozoraUS** [comment]
結局コードを書かないとサイトのデザインなどの変更ができないのはそうなんですよね、、。せめて、サイトの設定ファイルのようなものにテーマやテーマカラー、開催時刻などの基本的に変わることのないような情報をまとめておくのはどうでしょう？今は変更するのも楽になるし、可読性も向上すると思います。ノーコードで（デザインなどを変更しなければ）次の星陵祭のページを作ることができる程度のものは用意したいと思っているんですよね。

**Comment by hibiyahibiyahibiya** [comment]
う～～ん……気が乗らないなあ
それ作っても、十中八九新しい仕様に合わせて作り直さなきゃいけないだろうからなあ、って思っちゃって
「このファイルにカラーコードが、このファイルに開催時刻などが載ってますよ」っていうのを一つのpdf、ないし
(discordのメッセージでもいいけど)一つの文章にまとめて把握できるようにする、じゃだめ…？

**Comment by aozoraUS** [comment]
設定の仕方をwiki等に書いてそれがずっと使えるのならそれで全く問題ないと思うのですが、結局毎年仕様が変わると刷れば説明するためのwikiを作り直し続ける方が手間がかかると僕は思ってしまうんですよね。再利用しやすいものにしたい。
<img width="963" alt="スクリーンショット 2024-01-17 22 36 54" src="https://github.com/hibiya-itchief/quaint-wa/assets/74809407/ea550354-c4f9-450f-9579-d17218882694">
このような感じのファイルにまとめたい

**Comment by hibiyahibiyahibiya** [comment]
あーたしかにwikiの修正を入れなきゃっていうことはそうだね
でも、仕様を変える時の調整が大変っていうのと釣り合うよね

それと、根本的な話だけど単純に一つのファイルにその情報をまとめるメリットが薄くない……？と思っちゃった
そのファイルを見てわかる人間なら、discordに情報まとめたものでも別に問題なくない…？ていう

**Comment by aozoraUS** [comment]
仕様を変えるときは変数消すor追加するぐらいの手間しかかからないことを想定しているのですが、その仕組みを実装するのは難しいですかね?
何回も繰り返し使う値は一つのファイルにまとめてそれを変更すれば全てに適応される方が楽に僕は感じます。祭らいを抜くのissueに取り組んでいたときに感じた主観ですが。ファイルにまとめられたものを編集するのとvueページ編集するのだとかなりハードルの差があるように思うのですがどうでしょう?

**Comment by hibiyahibiyahibiya** [comment]
カラーコードについてだけ言えば、別に今でも、編集しようと思ったらmain.cssとnuxtconfig.tsのカラーコードを変更するだけでいいからスーパー楽だと思う（vueファイルは全く扱わなくていい）
それと、技術的な大変さの話については、いま上記ファイルに直でカラーコードを書いているのを、他のファイル参照にさせる方法がわかんないかな（純粋に試したことがないだけなんだけど）
GitHub Environmentsで実装できたりしないかな～～って思ってるけど

それと、カラーコード以外の要素があんまり思いつかないんだけど……
開催日付・時刻とかはそういうファイルに載せる内容じゃないと思うのと、日付とか時刻とかってhtmlページに直打ちで調整しながら入れた方がよくない……？

**Comment by aozoraUS** [comment]
[](https://v2.nuxt.com/docs/directory-structure/store/)
[](https://v3.vuex.vuejs.org/#what-is-a-state-management-pattern)
この辺が使うなら簡単そう。日付はなおさら入力ミスなくすためにこっちのほうが便利な気がします?基本的にデザインはタグとcssでいじっていて、表示する文字(全角半角とか?)で変えているわけではないと認識しているんですが、そこは自分理解浅いです。

**Comment by aozoraUS** [comment]
ご意見ありがとうございましたm(_ _)m
