### ISSUE TITLE
caseの統一について

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#43]
自分は今まで、
変数→snake_case
関数(method)→PascalCase (UpperCamelCase)
に統一するべきだと思ってたんだけど、

考え直した方がいいのかなあ…
https://qiita.com/am_nimitz3/items/7b01af53751dba5d8fb1

ただ、関数と変数は別形式の方が良いと思うのはゆるがない

変数snake_case, 関数lowerCamelCase, とかなのかな……

てかもしかしてeslintの設定で統一できる？
https://dev.classmethod.jp/articles/shuntaka9576-check-eslint/

**Comment by aozoraUS** [comment]
変数snake_case, 関数lowerCamelCaseにしませんか？PascalCaseはpythonでclassの命名に使うので

**Comment by hibiyahibiyahibiya** [comment]
じゃこれからはそれを採用しよう
けってい

**Comment by aozoraUS** [comment]
#48
