### ISSUE TITLE
/tickets スクショ対策

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#59]
そもそも必要か、という議論も行いたい。

https://github.com/hibiya-itchief/2023-quaint-app/issues/558

**Comment by aozoraUS** [comment]
チケットを係の人に見せるときにスクショできたほうが便利じゃないですか？不正なことをする人もいないでしょうという楽観的な見方ですが

**Comment by hibiyahibiyahibiya** [comment]
んーまあいいかなあというのはわかる
たしかに不正出来るシチュエーション、不正しなくていいだろっていう状況なんだよな

じゃあスクショ対策は今年は気にせずで行こうか
代わりに、受付担当者が画面をぱっと見で正しい整理券か判断しやすい画面にするよう心がけよう！
