### ISSUE TITLE
/admin CSV読み込んで公演を追加する機能

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#77]
今どうなっていたんだっけ?
@aozoraUS 

実現できたら、総務とかチーフとかといい感じに分担ができる

**Comment by aozoraUS** [comment]
APIは完成してて、フロントも完成してたと思います。

**Comment by aozoraUS** [comment]
あとは誰がその機能を使えるようにするかという感じです。

**Comment by aozoraUS** [comment]
[サンプルシート](https://docs.google.com/spreadsheets/d/1aJLgOH4i8c5RInaDZ5DIuK0s37WpnrltIGhpS6_EafM/edit?usp=sharing)

**Comment by aozoraUS** [comment]
この形式のファイルに羅列するで大丈夫ですか？これでいいなら全部出来上がってます

**Comment by hibiyahibiyahibiya** [comment]
とりあえず良いと思う！！
まじ感謝
