### ISSUE TITLE
トップページ　更新情報やお知らせ等は必要か

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#79]
https://github.com/hibiya-itchief/2023-quaint-app/issues/517

**Comment by aozoraUS** [comment]
チーフに意見求めてもよさそうですね。

**Comment by hibiyahibiyahibiya** [comment]
うーんでもハードル高くない？
どうやって実装するか考えなきゃ

**Comment by aozoraUS** [comment]
ハードルは高くないと思います。

**Comment by hibiyahibiyahibiya** [comment]
たしかに考えてみればそんなに高くないかも

お知らせ情報の入力元(forチーフ会)をどうするかっていうのぐらい？editみたいに自前で作るのは可能なら避けたいかも
もっといい手段があるような気がする

**Comment by aozoraUS** [comment]
外部のサービスを利用するってことですか?

**Comment by hibiyahibiyahibiya** [comment]
あーでもどうなんだろうね
どれくらいの機能が欲しいかで変わるかも
平文でいいなら、editページからパクるだけだし自前で作ってもいいかもね
でももっと装飾された文章であれば、こちらで制作するのは(暇じゃなければ)やめておいた方がいいような気がする

**Comment by aozoraUS** [comment]
平文でいいならもう作り終わりますよ

**Comment by hibiyahibiyahibiya** [comment]
優先度まだそんなに高くないから、いったん放置しておく？

**Comment by aozoraUS** [comment]
チーフから一応作っておいてくれと言われたものですし、そこまで装飾をつける文章を書くわけでもないと思うので簡単に実装しますよ。時間かからないと思います

**Comment by hibiyahibiyahibiya** [comment]
りょーかい

**Comment by aozoraUS** [comment]
<img width="505" alt="スクリーンショット 2024-05-11 15 35 13" src="https://github.com/hibiya-itchief/quaint-wa/assets/74809407/118d0711-001b-40c7-8d6f-97d1fd6bc1ff">
入れる情報はこれで大丈夫ですか？これでいいならすでにAPIは完成しました

**Comment by hibiyahibiyahibiya** [comment]
仕事が早すぎる
良いと思う！！

**Comment by ekkekuru2** [comment]
@aozoraUS 
detailがVARCHAR(255)は短いのでは？
TEXT()もしくはLONGTEXTのが良いかも
