### ISSUE TITLE
団体の画像の縦横比を設定する

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#8]
(クラ代に周知するため、早めに決定する)

フロントエンドでは自動で直すけども、指定の縦横比だと綺麗だからそれで送ってきてねっていう形式？

2023.では縦長と横長があり、団体によって見づらくなっていたりしたら申し訳なかった
なので統一して、スマホ表示もPC表示も全部見やすくなるようにしたい

縦長、横長どっちにするかは未定…スマホ表示は縦長だけど

**Comment by aozoraUS** [comment]
縦長と横長どちらにしますか？個人的にはスマホが縦なら縦表示でいいと思います。

**Comment by hibiyahibiyahibiya** [comment]
# 参考

<img width="500" src="https://github.com/hibiya-itchief/quaint-wa/assets/128669695/729a2d57-e512-4a8a-a9f1-e06a4aa598ab">

参考として現行表示、18R,22Rは元画像が縦、21Rは横、18Rはおそらく正方形ぐらい

![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/352117f4-1876-40d7-94da-a6ffa8dae27d)

これがPC表示

# .

ほとんどのユーザーがスマホだから、PCでも縦表示で統一する方向なのは良いと思う
ただ、23Rの4771とか、横表示ですごいしっくりくるものをどうしようかな

**Comment by hibiyahibiyahibiya** [comment]
今スマホだと強制的に何対何に直されてるんだろう？
その比率をeditページに書く、ぐらいしかできることなかったりする……？
規定を満たさない画像をアップロードできないようにするのはあんまりしたくないんだよね

**Comment by aozoraUS** [comment]
今スマホではheight 120px width 90pxで設定されてるようです。pcはwidth/heightが4/3で設定されています。画面に収まりきらないときの自動トリミングをしないように設定されているのでそれが正方形とかに見える原因だと思います。

**Comment by aozoraUS** [comment]
縦:横、今のスマホの表示と同じで4:3で統一にしますかね?

**Comment by hibiyahibiyahibiya** [comment]
そうだね了解
そしたらスマホ表示と同じように、左に画像、右にタイトルなどっていう配置でやってほしい！！
descriptionの表示行を多くしたり、全体的に文字サイズ大きくする、とかが良さげだと思う

**Comment by hibiyahibiyahibiya** [comment]
* #20
