### ISSUE TITLE
/groupsと/_groupId ブックマーク機能を改善する

### ISSUE THREAD

**Issue by hibiyahibiyahibiya** [hibiya-itchief/quaint-wa#9]
2023.ではLocal Storageを使用したが、localstorageはキャッシュとして大きすぎるので極力使いたくないです
(また、localstorageはcreatedじゃ使えずmountedを使う必要があり、コードが乱雑になってしまう)

個人的に考えているのは、ブックマーク機能をログイン者専用の機能にして、ブックマークしているかどうかはAPIを通すというもの
ただこれだとAPIに負荷かかるので採用したくないのと、ログインしていない人はブックマーク機能をつかえないというデメリットはある

なんかいい案ください

**Comment by hibiyahibiyahibiya** [comment]
ブラウザのブックマーク機能を利用するのどうでしょ
すごい楽

https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/get

ただし、一部使えないブラウザがあることを記載する必要あり

**Comment by hibiyahibiyahibiya** [comment]
色々調べたけど、
CookieかLocalStorageかAPIかくらいが実用的で、
cookieは規制とかそれ以外にも実装が大変そう、あと通信が多くなるかも（？）
LocalStorageはキャッシュとして巨大すぎる、
APIはログイン前提かつ恒常的な負荷になるのが良くない

から、ブックマーク機能廃止してもいいんじゃないかなーというのが正直な所。
それにブラウザに備わってるブックマークで十分といえば十分だしねー

**Comment by aozoraUS** [comment]
今ブックマークで使っているキャッシュはそんなに大きいのですか？せっかく作ったものだからとりあえず残していいと思います

**Comment by hibiyahibiyahibiya** [comment]
> けれど忘れてはならないのはlocalStorageのデータは大容量かつ永続的であるということ。
>
> sessionStorageならばブラウザのタブを閉じるだけで削除されますが、localStorageは実装者がデータを削除するプログラムを用意しない限り、永遠に保持され続けられます。
>
> しかもユーザー側からすれば、cookieとWebStorageどちらを使っているかは分からない。
>
> 一般的なユーザーがDeveloper toolsを開くことなどありません。
> ブラウザによっては「ブラウザの履歴とcookie削除」をしてもlocalStorageのデータは保持されるものも少なくない。
> しかし、ほとんどのサイトではユーザーが任意にlocalStorageを削除できるインターフェースを用意していない。
> ならばlocalStorageに保存されたデータはどうなるのだろう？
>
> 多くのサイトでlocalStorageを使うようになれば
> ユーザーのデバイス（のストレージ）には消すことのできないジャンクデータがどんどん蓄積されていってしまう。
> それなのに、localStorageを使用して良いかユーザーに確認する「confirm」も用意していない。
> これはユーザーフレンドリーな実装だろうか？
> [このサイト](https://glitter-style.jp/labo/web-resource/manner-of-webstorage/)より

だから、あんまりLocalStorageそのものを利用したくなかったんだけど…

まあ、ブックマークを外せばいいだけだし、それに些細なことなのはそうだからねー……

そんな些細なこと気にしなくていいだろと思うなら、そんままで行ってもいいかもね
